# Generated by Django 3.0.5 on 2020-08-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200816_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='property_id',
        ),
    ]
