# Generated by Django 3.0.5 on 2020-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretkey', '0002_remove_otpmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
