# Generated by Django 3.0.5 on 2020-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretkey', '0003_otpmodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
